export const articleList = [
  {
    id: 1,
    title: 'An AI capable of generating realistic images',
    category: 'art',
    subCategory: ['art', 'technology', 'AI'],
    description:
      "This video is an extract from the Nightcap TV show presented by Jon Sarlin and posted on CNN Business last Saturday. He hosted Jerry Saltz, an art critic from New York Magazine who judges the art using DALL-E-2, an AI system that can create realistic images from a description in natural language. According to Jerry Saltz, AI art has no creativity and imagination. But in the future, it could be used as a tool and an evolution of art like the camera in the 19th century. So we can ask ourselves if AI will replace the artist? It’s difficult to answer because all great artists have their own signature by their artistic techniques and it is difficult to imitate it. Also, the AI doesn't have a human side that is expressed through the creation. So AI can't replace the artist but can be used for artistic purposes. And, it could be a good way to make art without knowing how to draw or paint.",
    authorName: 'CNN',
    authorAvatar: '/assets/images/cnn.png',
    createdAt: 'September 06, 2022',
    cover: '/assets/images/ai-art.png',
    video: '/assets/videos/ai-art.mp4',
  },
  {
    id: 2,
    title: 'The dangers of deepfake explained by a cybersecurity expert',
    category: 'technology',
    subCategory: ['AI', 'deepfake', 'dangers', 'cybersecurity'],
    description:
      "This video is a clip from the Unfiltered TV Show, presented by Dan Bongino and posted last Sunday on the Fox News website. In this clip, the cybersecurity expert Morgan Wright explains the dangers of deepfake video technology, an artificial intelligence technique that can reproduce a face. As he said, the deepfake technology can be used to convince people by imitating famous persons. And even if it’s wrong, there will always be people who believe it. So, it can be dangerous in cases like the war in Ukraine. And the worst thing is that once the video is uploaded, it is already too late. What is interesting in this video is how technology can influence people's thinking. Like fake news, it can change our vision or our way of thinking, and that’s why it’s important to check if it’s true or not.",
    authorName: 'Fox News',
    authorAvatar: '/assets/images/fox-news.png',
    createdAt: 'September 12, 2022',
    cover: '/assets/images/deepfake-video.png',
    video: '/assets/videos/deepfake-video.mp4',
  },
  {
    id: 3,
    title: 'Is your Twitter information private ?',
    category: 'technology',
    subCategory: ['cybersecurity', 'dangers', 'twitter'],
    description:
      "This video is a clip from the Ingraham Angle TV Show, presented by Laura Ingraham and posted last Saturday on the Fox News website. In this clip, we can see the Missouri Senator Josh Hawley who shares information about the access to user data by Twitter engineers. According to Josh Hawley, it’s very problematic because Twitter engineers have access to all the accounts in the world and can do whatever they want, anytime they want. So, they can post anything. We can ask ourselves how the big tech companies are using our data ? It can be used for commercial or political purposes. It may be the case for other social networks. So we have to be careful with our privacy.",
    authorName: 'Fox News',
    authorAvatar: '/assets/images/fox-news.png',
    createdAt: 'September 20, 2022',
    cover: '/assets/images/twitter-account.png',
    video: '/assets/videos/twitter-account.mp4',
  },
  {
    id: 4,
    title: 'The incredible rescue of a baby by two bus drivers',
    category: 'other',
    subCategory: ['rescue', 'school', 'car theft'],
    description:
      "This video is a clip posted yesterday on the ABC News website. In this video, a car was stolen with a baby inside. So, the parents asked a driver for help. The first driver called the police and informed the radio station. And the second driver, after receiving the message, went around the neighborhood to bring the baby back. Fortunately, the baby was not hurt. What is impressive is the kindness of the drivers who reacted immediately. It was a typical day for them, but they didn't hesitate to help the parents. And they could get some action.",
    authorName: 'ABC News',
    authorAvatar: '/assets/images/abc.png',
    createdAt: 'October 10, 2022',
    cover: '/assets/images/bus-driver.png',
    video: '/assets/videos/bus-driver.mp4',
  },
  {
    id: 5,
    title: 'The impact of e-waste by the numbers',
    category: 'other',
    subCategory: ['technology', 'e-waste', 'ecology'],
    description:
      "This video is a clip from By The Numbers, posted this weekend on the ABC News website. In this video, we can see the dangers of electronic waste by numbers. They estimate that 81,000 electronic devices will be thrown away and a small percentage will be recycled. And the big problem is that chemicals products and metals contaminate the soil and the groundwater and the price of the resources increase strongly. So the advocates ask users to recycle or repair their electronics devices. In the future, there could be laws forbidding brands such as Apple to promote the regular purchase of electronic devices or simply a restriction on the number of purchases.",
    authorName: 'ABC News',
    authorAvatar: '/assets/images/abc.png',
    createdAt: 'October 17, 2022',
    cover: '/assets/images/e-waste.png',
    video: '/assets/videos/e-waste.mp4',
  },
  {
    id: 6,
    title: '"Moonwalkers", a new generation of shoes ?',
    category: 'technology',
    subCategory: ['robotics', 'AI', 'gadgets'],
    description:
      "This video is a clip from the CNN website posted last week. In this video, we can see  battery-powered shoes called “moonwalkers”, invented by Shift Robotics. The purpose of these shoes is to increase our speed when we walk, which is very interesting when we are late for school, or for jobs that require walking. They calculate the walker's speed and acceleration and automatically adjust the motor speed, so there is no imbalance when we walk. All the user has to do is to walk faster to accelerate or slower to decelerate. Moonwalkers may encourage people to walk and possibly reduce obesity in the United States. They are more ecological than the car and easier than the bike, so it could be a good way to move easily and quickly. Today, the users can walk over 6 miles after a single charge of an hour and a half. But maybe in the future, these shoes will be more powerful and more aesthetic. And maybe they will have new features.",
    authorName: 'CNN',
    authorAvatar: '/assets/images/cnn.png',
    createdAt: 'November 07, 2022',
    cover: '/assets/images/battery-powered.png',
    video: '/assets/videos/battery-powered.mp4',
  },
  {
    id: 7,
    title: 'The solution to limit CO2 emissions from aircraft',
    category: 'science',
    subCategory: ['chemistry', 'buisness', 'ecology'],
    description:
      "This video comes from the CNN website, and was posted last week. In this video, we can see the start-up Air Company, which has invented a carbon-neutral jet fuel made from carbon dioxide present in our atmosphere. The production process is simple : they take carbon dioxide, combine it with hydrogen and turn it into fuel which becomes a feedstock thanks to a distillation platform. The company used this process to create a CO2-derived vodka that is carbon neutral and carbon negative. Now, they say they can use the same process to power jets without impacting the atmosphere. Their jet fuel is a great advance for their company and for the aviation industry. And maybe in the future they will develop new solutions to limit carbon dioxide emissions.",
    authorName: 'CNN',
    authorAvatar: '/assets/images/cnn.png',
    createdAt: 'November 14, 2022',
    cover: '/assets/images/carbon-neutral.png',
    video: '/assets/videos/carbon-neutral.mp4',
  },
  {
    id: 8,
    title: 'These drones are more than necessary for firefighters',
    category: 'technology',
    subCategory: ['robotics', 'chemistry', 'support'],
    description:
      "This video comes from the CNN website, and was posted last week. In this video, we can see the start-up Drone Amplified which uses drones to help firefighters prevent extreme fires and save their lives. The technique used by drones is called : prescribed burns. To sum up, it's about fighting fire with fire. The drones drop “dragon eggs” which are balls that react with fire to create a fire. Yeah that sounds weird. The goal of prescribed burns is to burn at low intensity the dead leaves and sticks that can cause major wildfires. Before, the firefighters had to burn them by hand with a grip torch, which could be dangerous. Now they can drop the dragon eggs with the drones and even define a burn limit. For the moment, a drone can wear over 400 fireballs. But maybe in the future they will be able to wear thousands and will be better protected.",
    authorName: 'CNN',
    authorAvatar: '/assets/images/cnn.png',
    createdAt: 'November 21, 2022',
    cover: '/assets/images/fireballs.png',
    video: '/assets/videos/fireballs.mp4',
  },
  {
    id: 9,
    title: 'A NASA rover discover past of life',
    category: 'science',
    subCategory: ['robotics', 'chemistry', 'aerospatial'],
    description:
      "This video comes from the CNN website, and was posted last week. It deals with the discovery of rocks by a NASA rover on the planet Mars. These rocks were formed by volcanic processes which were affected by the action of liquid water. And as we know, water is a basic need for life. NASA also observed organic molecules like carbon, hydrogen, and oxygen thanks to an instrument called SHERLOC that can search for organic or mineral materials. So it proves that there was a form of life on Mars. So if in the future, we can implement raw materials, we will be able to live on Mars.",
    authorName: 'CNN',
    authorAvatar: '/assets/images/cnn.png',
    createdAt: 'November 21, 2022',
    cover: '/assets/images/past-of-life.png',
    video: '/assets/videos/past-of-life.mp4',
  },
  {
    id: 10,
    title: 'A new feature on Iphone that can save us',
    category: 'technology',
    subCategory: ['IoT', 'technology', 'Support'],
    description:
      "This video comes from the CNN website, and was posted last week. It deals with the new Iphone 14 feature that allows users to connect to an emergency device which is very useful when we are in danger. All we have to do is answer the questions and follow the instructions. After that the collected data will be sent as a message to a dispatcher. This feature can be used for all types of problems such as injuries, car problems, orientation problems or even crimes. But the disadvantage, we have to establish a stable connection with the satellite. This new feature is very useful when we know that crimes in the United States are increasing every day.",
    authorName: 'CNN',
    authorAvatar: '/assets/images/cnn.png',
    createdAt: 'December 05, 2022',
    cover: '/assets/images/secure-feature.png',
    video: '/assets/videos/secure-feature.mp4',
  },
  {
    id: 11,
    title: 'A chatbot leading to a nightmare scenario',
    category: 'technology',
    subCategory: ['AI', 'technology', 'Future'],
    description:
      "This video comes from the CNN website, and was posted last week. It deals with the new AI Chatbot from OpenAI called ChatGPT which is able to generate a whole text from props. And for the fun fact, the introduction to this TV Show was written by ChatGPT. But this chatbot can lead to important problems. Like the deep fake, it can be used to manipulate people by writing absolutely false but convincing texts or contents thanks to its advanced algorithm. The other problem is that it can end jobs such as customer service. Unlike a human, the ChatGPT has the ability to retain each customer and their emotion, and after, generate a script to sell them what they want. So, this bot represents a great technological advance that can be used in many jobs. But, it’s necessary to restrict its access to avoid a nightmare scenario.",
    authorName: 'CNN',
    authorAvatar: '/assets/images/cnn.png',
    createdAt: 'December 11, 2022',
    cover: '/assets/images/ai-chatbot.png',
    video: '/assets/videos/chatgpt.mp4',
  },
];
